FROM maven:3.9.11-eclipse-temurin-25

WORKDIR /app

# copy pom first for layer caching
COPY pom.xml .

# download dependencies
RUN mvn dependency:go-offline

# copy source code
COPY src ./src

# build the jar
RUN mvn clean package -DskipTests

# expose your spring port
EXPOSE 8000

# run the app
CMD ["java", "-jar", "target/backend-0.0.1-SNAPSHOT.jar"]
