spring.application.name=backend

server.port=8000
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
jwt.secret=${JWT_SECRET}
app.frontend-url=http://localhost:5173

# pay attention to what container you target
spring.datasource.url=jdbc:postgresql://pgvector:5432/postgres
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.main.allow-bean-definition-overriding=true
spring.ai.openai.api-key=${OPENAI_API_KEY}
# to select model of embeding(how embeding appears)
spring.ai.openai.embedding.options.model=text-embedding-ada-002
#make the create the schema
spring.ai.vectorstore.pgvector.initialize-schema=true
#not relying on defaults,declare the dimensions
spring.ai.vectorstore.pgvector.dimensions=1536
